import zope.interface

from z3c.form import interfaces

from z3c.form.browser.select import SelectWidget
from z3c.form.widget import FieldWidget


class DGFTreeSelectWidget(SelectWidget):
    """
    A data grid widget which does nested master-slave
    drop down menus using <select>.
    """

    klass = u'dgf-tree-select-widget'

    def __init__(self, request):
        SelectWidget.__init__(self, request)

        # Dynamically generated by Javascript
        self.terms = []

    @property
    def items(self):
        return []


@zope.interface.implementer(interfaces.IFieldWidget)
def DGFTreeSelectFieldWidget(field, request):
    """IFieldWidget factory for SelectWidget."""
    return FieldWidget(field, DGFTreeSelectWidget(request))
